server:
  port: 80
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.25.138:3306/sale
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 1000
      initial-size: 100
      min-idle: 500
  #配置redis
  redis:
    host: 192.168.25.138
    timeout: 50000
    lettuce:
      pool:
        max-active: 1000 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 10 # 连接池中的最小空闲连接
        max-idle: 500 # 连接池中的最大空闲连接
#配置mybatis
mybatis:
  mapper-locations: classpath:com.java.sale.dao.mapper/*.xml
  type-aliases-package: com.java.sale.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl