server:
  port: 80
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/sale?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 192.168.25.138
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
#配置mybatis
mybatis:
  mapper-locations: classpath:com.java.sale.dao.mapper/*.xml
  type-aliases-package: com.java.sale.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 300